### PR TITLE
Sound setting bug

### PR DESCRIPTION
**Pull request by renaiku**
When I set the sound to 60, I hit back then return in the sound setting, and the sound is on 59.
If i put 61, back, return to the menu, the sound is set to 60 ... etc

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
That's quite a PR, didn't you wanted to PR on the recalbox repository ?

**Comment by renaiku** [comment]
Well I googled and found this page: https://github.com/recalbox/recalbox-os/wiki/Signalement-de-bugs-(FR)

It tells me to post here the bugs on the interface of ES.

**Comment by digitalLumberjack** [comment]
You created a PR issue, that's not what you wanted to do :) To report a bug, on recalbox, just create an issue on https://github.com/recalbox/recalbox-os/issues
We are updating the wiki page

**Comment by digitalLumberjack** [comment]
Can you close this one ?

**Comment by renaiku** [comment]
Ok, thanks. Reposted on the good link. Closed.

**Pull request closed without merging**
