### PR TITLE
Ui modes kiosk kid full

### PR DESCRIPTION
**Pull request by elliscnck**

### CODE REVIEW

**Comment by t3hi3x** [comment]
Hi @elliscnck - Can you start an issue or reply to https://github.com/Herdinger/EmulationStation/issues/20 on the Herdinger fork? We're thinking about a generic design that would cover several requirements for managing large libraries. Specifically, I'd love you to outline the requirements you have for this feature, so they can be considered for the generic version.

**Comment by robertybob** [comment]
@elliscnck  I'm confused, isn't this all the idea/work of @zigurana ? Are you trying to merge all of his commits or just a select few you'd like for the @t3hi3x branch?

**Comment by zigurana** [comment]
@robertybob, everyone is free to create a pull-request, even @elliscnck ;-). It's just not very likely that Aloshi is going to pick it up anytime soon, or did I miss something.
If @t3hi3x is going to pick up further development of EmulationStation, I am more that willing to discuss this and other features with him.

**Comment by t3hi3x** [comment]
Sorry guys - wasn't paying attention to the source :)

For others wanting to collaborate on this design, please comment out here: https://docs.google.com/document/d/1J7PXBnFqU_8KVYOtlwxjADvUC4TcUTEmHOa7KkR0sSU/edit#

**Pull request closed without merging**
