### PR TITLE
Fix linux (fedora) compilation issues

### PR DESCRIPTION
**Pull request by codinghipster**
I can't compile on Fedora 24, I think this is the source of the issue

### CODE REVIEW

**Comment by thias** [comment]
Thanks a lot! I can confirm that this fixes compilation on Fedora 24 for me too. I have now updated my packages at http://dl.marmotte.net/rpms/fedora/24/x86_64/ and spec files at https://github.com/thias/retroarch-fedora/.

**Comment by theist** [comment]
This PR also fixed the same compilation error described in #591 on a ubuntu GNU/Linux 16.10

**Comment by grantbacon** [comment]
This also fixes my compilation errors on Debian Stretch

**Comment by robindegen** [comment]
This also fixed the problem for me on ubuntu 17.04. Why wasn't this or a similar fix merged?

**Comment by danieloconell** [comment]
Why hasn't this PR been accepted it fixes broken code on the master branch?

**Comment by robindegen** [comment]
@danieloconell Because apparently they moved all development to RetroPi/EmulationStation and it's probably maybe integrated there. It's just not very clear that they've done so.

**Comment by kpksmiley** [comment]
What code do you use to get the files? I keep getting an error saying unable to locate package, when I used:
sudo apt-get install http://dl/marmotte.net/rpms/fedora/24/x86_64

**Review by kasi09 — COMMENTED** [review]
Great Job !!
Work on Debian/Stretch Rock64.

**Comment by codinghipster** [comment]
@Aloshi are you accepting PRs, and is this still the most active repo?

**Comment by robindegen** [comment]
@codinghipster It's not. Look at the last commit dates. They are all from a few years ago. The up-to-date repo is at RetroPi/EmulationStation as I mentioned above.

**Comment by theist** [comment]
@robindegen seems that this repo is unmantained and the current one is https://github.com/RetroPie/EmulationStation

**Comment by codinghipster** [comment]
@Aloshi's website and repo are still the first results on google when searching for emulation station, it would be nice to see this repo and /or website updated

**Comment by robindegen** [comment]
@codinghipster Yes, but apparently he's disappeared and doesn't really update anything anymore. So the new project can't update this stuff.

**Comment by Aloshi** [comment]
Better late than never, I suppose

**Comment by lewsidius** [comment]
Really noob question how do you implement this fix? Do I edit or add script somewhere? Getting better at it and mainly work on retropie. sorry still learning

**Pull request merged**
